version: 0.2
phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=
      - echo install step...
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t codebuildapp:latest .
      - docker tag codebuildapp:latest <700523735250.dkr.ecr.us-east-1.amazonaws.com/codebuildapp>/codebuildapp:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push <700523735250.dkr.ecr.us-east-1.amazonaws.com/codebuildapp>/codebuildapp:latest
